apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4i-16.1.1-
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  pipelineRef:
    name: cp4i-16.1.1
  params:
  - name: COPY_TLS_CERTS
    value: false
  serviceAccountName: pipeline
  timeout: 6h0m0s
  podTemplate:
    securityContext:
      fsGroup: 65532